---
  - name: "copy artifact"
    become: true
    copy:
      src: artifact.tar.gz
      dest: ~/

  - name: extract zipped artifact and install dependancies
    become: true
    shell: |
      tar -xvzf ~/artifact.tar.gz
  
  - name: "Install Node.js 13"
    shell: |
      # Install Node.js
      curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
      sudo apt-get install -y nodejs

      # Use n version manager to use Node.js v13.8.0
      sudo npm install -g n
      sudo n 13.8.0
 
  
  - name: "install pm2"
    become: true
    npm:
      name: pm2
      global: yes
      production: yes
      state: present 

  # - name: "stop default"
  #   become: true
  #   command: # pm2 stop default  

  - name: "start app"
    become: true
    shell: |
      cd ~/
      npm install 
      sudo pm2 stop default
      sudo pm2 start npm -- start
    
