---
  - name: "extract artifact"
    unarchive:
      src: ~/project/artifact.tar.gz
      dest: /home/ubuntu
 
  - name: "Install Node.js 13"
    shell: |
      # Install Node.js
      curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
      sudo apt-get install -y nodejs

      # Use n version manager to use Node.js v13.8.0
      sudo npm install -g n
      sudo n 13.8.0
 
  
  - name: "install pm2"
    become: true
    npm:
      name: pm2
      global: yes
      production: yes
      state: present 

  - name: "Installing Node Dependencies"
    become: true
    shell: |
      npm install

  - name: "start app"
    become: true
    shell: |
      sudo pm2 stop default
      sudo pm2 start npm -- run start
    


#  - name: "Configure pm2"
#     shell: |
#       sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
#       sudo pm2 save


