---
  - name: "extract artifact"
    become: yes
    unarchive:
      src: files/artifact.tar.gz
      dest: .
 
  - name: "Install Node.js 13"
    shell: |
      # Install Node.js
      curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
      sudo apt-get install -y nodejs

      # Use n version manager to use Node.js v13.8.0
      sudo npm install -g n
      sudo n 13.8.0
 
  
  - name: "install pm2"
    become: true
    npm:
      name: pm2
      global: yes
      state: latest
      production: yes
     
  - name: "start app"
    become: true
    shell: |
      pm2 stop all
      pm2 start npm -- start
    


#  - name: "Configure pm2"
#     shell: |
#       sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
#       sudo pm2 save


