---
  - name: "copy artifact"
    become: true
    copy:
      src: ~/project/artifact.tar.gz
      dest: ~/

  - name: extract zipped artifact and install dependancies
    become: true
    shell: |
      tar -xvzf ~/artifact.tar.gz
  
  - name: "Install Node.js 13"
    shell: |
      # Install Node.js
      curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
      sudo apt-get install -y nodejs

      # Use n version manager to use Node.js v13.8.0
      sudo npm install -g n
      sudo n 13.8.0
 
  
  - name: "install pm2"
    become: true
    npm:
      name: pm2
      global: yes
      production: yes
      state: present 



  - name: "Installing Node Dependencies"
    shell: |
      cd ~/
      npm i

  # - name: "stop default"
  #   become: true
  #   command: # pm2 stop default  

  - name: "start app"
    become: true
    shell: |
      cd ~/dist
      
      sudo pm2 stop default
      sudo pm2 start main.js
      sudo pm2 start npm -- start
    
    register: execute_node

  - name: "Configure pm2"
    shell: |
      sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
      pm2 save


